### ISSUE TITLE
contact information

### ISSUE THREAD

**Issue by elgarbe** [heron/heron_simulator#4]
Hi, I will use this simulator for a research paper, could you provide information for referring for this project? 
Can I get e-mail address of a developer of this package?

thank

**Comment by civerachb-cpr** [comment]
I imagine you've already finished your paper since this is over a year later.  But this package was developed by Clearpath Robotics.  Maintainer email addresses are available in the package information, or you can DM the maintainers directly if you still need the information.
I hope your research paper went well!
