### ISSUE TITLE
Velocity not achieved

### ISSUE THREAD

**Issue by elgarbe** [heron/heron_simulator#5]
Hi, I'm using your simulator and notice that velocity set point (I publish 0.5 to /cmd_vel topic) is not achieved, it gets to 0.45 or so, but not 0.5. Why is that?

**Comment by civerachb-cpr** [comment]
I'm not sure if this is still a problem for you, but I just tested this and couldn't replicate the behaviour you describe.  It could be either a bug that was fixed in the last year, or it could be something like the currents in the simulated water acting against the robot and slowing down its absolute velocity.
