### ISSUE TITLE
Unable to move 2/more herons using RViz

### ISSUE THREAD

**Issue by vivekrathi14** [heron/heron_simulator#9]
I am launching 2 different herons. I am unable to move those robots using interactive markers in RViz.
I added both robot models and also updated interactive markers for the same. I use` namespace/odom` frame as reference in RViz.

Following are the used commands-
```
roslaunch uuv_gazebo_worlds lake.launch
roslaunch heron_gazebo spawn_heron.launch namespace:=heron1
roslaunch heron_gazebo spawn_heron.launch namespace:=heron2 x:=2 y:=2 yaw:=1
roslaunch heron_viz view_robot.launch
```

Even if I do below mentioned command, I am not able to move robot using interactive markers in RViz.
`roslaunch heron_gazbeo heron_world.launch namespace:=heron1`

In either case I was able to move robot by publishing to `<namespace>/cmd_drive` on terminal.

**Comment by civerachb-cpr** [comment]
This is likely due to that issue we had with the magnetometer simulation breaking (see https://github.com/heron/heron_simulator/pull/6).  It looks like the python script we added as a work-around isn't applying the namespace correctly.  I'll see about fixing that.
In the meantime you should be able to work around the problem by disabling the magnetometer by changing
`<param name="~use_mag" value="true" />`
to
`<param name="~use_mag" value="false" />`
in spawn_heron.launch.

**Comment by vivekrathi14** [comment]
Recent pull with updated code base got it fixed. Thanks :)
